packages:
  - apps/*
  - packages/*
  - proto

catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@faker-js/faker': ^9.9.0
  '@grpc/grpc-js': ^1.13.4
  '@grpc/proto-loader': ^0.7.15
  '@grpc/reflection': ^1.0.4
  '@nestjs/cli': ^11.0.7
  '@nestjs/common': ^11.1.5
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.1.5
  '@nestjs/microservices': 11.1.5
  '@nestjs/platform-express': ^11.1.5
  '@nestjs/schematics': ^11.0.5
  '@nestjs/testing': ^11.1.5
  '@nuxt/fonts': 0.11.4
  '@nuxt/icon': 1.15.0
  '@nuxt/image': 1.10.0
  '@nuxt/ui': 3.2.0
  '@phaicom/eslint-config': ^0.3.5
  '@prisma/client': ^6.12.0
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.0
  '@tailwindcss/vite': ^4.1.11
  '@types/express': ^5.0.3
  '@types/jest': ^30.0.0
  '@types/node': ^22.16.5
  '@types/supertest': ^6.0.3
  dotenv: ^17.2.0
  eslint: ^9.31.0
  eslint-plugin-better-tailwindcss: ^3.6.3
  eslint-plugin-format: ^1.0.1
  globals: ^16.3.0
  grpc-health-check: ^2.0.2
  jest: ^30.0.4
  lint-staged: ^16.1.2
  nuxt: ^4.0.0
  prisma: ^6.12.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  simple-git-hooks: ^2.13.0
  source-map-support: ^0.5.21
  supertest: ^7.1.3
  tailwindcss: ^4.1.11
  ts-jest: ^29.4.0
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  ts-proto: ^2.7.5
  tsconfig-paths: ^4.2.0
  tsup: ^8.5.0
  turbo: ^2.5.5
  typescript: ^5.8.3
  vue: ^3.5.17
  vue-router: ^4.5.1
