packages:
  - apps/*
  - packages/*
  - proto

catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@nuxt/fonts': 0.11.4
  '@nuxt/icon': 1.15.0
  '@nuxt/image': 1.10.0
  '@nuxt/ui': 3.2.0
  '@phaicom/eslint-config': ^0.3.5
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.16.4
  eslint: ^9.31.0
  eslint-plugin-better-tailwindcss: ^3.6.3
  eslint-plugin-format: ^1.0.1
  globals: ^16.3.0
  lint-staged: ^16.1.2
  nuxt: ^4.0.0
  simple-git-hooks: ^2.13.0
  tailwindcss: ^4.1.11
  turbo: ^2.5.5
  typescript: ^5.8.3
  vue: ^3.5.17
  vue-router: ^4.5.1
